.github/actions/build-docs/action.yml, .github/actions/build-frontend/action.yml, .github/actions/setup-node/action.yml, .github/actions/setup-python/action.yml, .github/workflows/codecov.yml, .github/workflows/main.yml, .github/workflows/release-drafter.yml, .github/workflows/release-trigger.yml, .github/workflows/release.yml, .github/workflows/website-preview.yml
=> Add GitHub Actions

admin-frontend/src/features/subsribeConfigManager/SubscribeModal.tsx
=> 修复前端两次点击编辑不能正确显示的问题

poetry.lock, pyproject.toml, src/plugins/nonebot_bison/platform/weibo.py, src/plugins/nonebot_bison/utils/http.py, tests/platforms/test_weibo.py
=> :bug: download weibo pics in `parse`

src/plugins/nonebot_bison/platform/bilibili.py, tests/platforms/test_bilibili_bangumi.py, tests/platforms/test_bilibili_live.py
=> fix(bilibili-live): 修正一些错误的api

admin-frontend/src/features/subsribeConfigManager/subscribeConfigSlice.ts
=> 修复后台无法删除 RSS 订阅的问题

src/plugins/nonebot_bison/__init__.py
=> fix require name

src/plugins/nonebot_bison/__init__.py
=> 适配 Nonebot 插件元数据

src/plugins/nonebot_bison/scheduler/aps.py, src/plugins/nonebot_bison/send.py, tests/test_send.py
=> 解决使用队列发送时产生大量日志的问题

src/plugins/nonebot_bison/config/migrations/4a46ba54a3f3_alter_type.py
=> 修复使用 PostgreSQL 时迁移脚本的报错

nonebot_bison/admin_page/__init__.py
=> 在未安装 fastapi 时不加载 webui

nonebot_bison/scheduler/scheduler.py
=> 调整 scheduler log level

docs/usage/README.md, nonebot_bison/platform/platform.py, nonebot_bison/plugin_config.py
=> 可以关闭日志中的网络报错

docs/usage/README.md
=> 修复文档中指向的nonebot2文档url

nonebot_bison/platform/bilibili.py, tests/test_config_manager_add.py
参考https://github.com/SK-415/bilireq/pull/18
解决添加Blibili订阅时，获取用户名时的报错
=> 解决添加Blibili订阅时，获取用户名时的报错

nonebot_bison/config_manager.py
fix https://github.com/felinae98/nonebot-bison/issues/237
=> 修复订阅 RSS 时，输入链接被转义的问题

.gitignore, nonebot_bison/platform/bilibili.py, nonebot_bison/utils/__init__.py
1. 增加了相似度计算前文本的预处理
2. 修复视频简介多余空格的bug
=> 修复bilibili推送的一些格式错误

nonebot_bison/post/plain_post.py, tests/post/test_plain_post.py
=> 修复RSS推送时没有URL消息的bug

poetry.lock, pyproject.toml
=> :arrow_up: 放宽 datastore 的依赖限制

.github/dependabot.yml
中国有句古话叫做识时务者为俊杰，想必眼下的这次修改一定能撬动阁下的检查
=> :bug: update-types应为array

docs/usage/README.md, docs/usage/easy-use.md, nonebot_bison/admin_page/__init__.py, nonebot_bison/plugin_config.py, tests/test_admin_page.py
=> BISON_OUTER_URL配置改进

.prettierrc
借鉴自 nonebot/nonebot2/pull/2546
=> 🔧 更新 prettier 配置

nonebot_bison/admin_page/types.py
=> 修复后台管理界面无法获取群信息的问题

nonebot_bison/admin_page/__init__.py, nonebot_bison/plugin_config.py, poetry.lock, pyproject.toml, tests/test_admin_page.py
=> 使用 yarl.URL 拼接 outer_url

nonebot_bison/platform/bilibili.py, nonebot_bison/platform/ncm.py, nonebot_bison/platform/platform.py, nonebot_bison/platform/weibo.py, nonebot_bison/sub_manager/add_sub.py, tests/sub_manager/test_add.py
允许在添加订阅阶段，parse_target方法抛出该错误时，向用户提供更多信息
https://github.com/MountainDash/nonebot-bison/blob/8cfeeacd86231f6f4835b3300235adb92eb13942/nonebot_bison/sub_manager/add_sub.py#L89-L92
=> ParseTargetException可以携带prompt参数

docs/dev/README.md
文档关于前端开发的部分，从yarn迁移到pnpm的过程中出现了一些小问题，建议修改
=> 修复前端开发部分文档的问题

renovate.json
参考 https://docs.renovatebot.com/presets-default/#semanticcommittypeallarg0
=> 🔧 更新 renovatebot 配置

nonebot_bison/utils/site.py
=> 修复 anonymous_site() 无法正确工作的问题

nonebot_bison/platform/rss.py, tests/platforms/test_rss.py
=> Rss 不再删除格式化字符

.pre-commit-config.yaml, nonebot_bison/config/subs_io/nbesf_model/v1.py, nonebot_bison/config/subs_io/nbesf_model/v2.py, nonebot_bison/platform/bilibili/retry.py, nonebot_bison/platform/bilibili/scheduler.py, nonebot_bison/platform/weibo.py, nonebot_bison/script/cli.py, nonebot_bison/sub_manager/__init__.py, poetry.lock, pyproject.toml, tests/config/test_config_legacy.py, tests/config/test_config_operation.py, tests/conftest.py, tests/platforms/test_arknights.py, tests/platforms/test_bilibili.py, tests/platforms/test_bilibili_bangumi.py, tests/platforms/test_bilibili_live.py, tests/platforms/test_ceobecanteen.py, tests/platforms/test_ff14.py, tests/platforms/test_ncm_artist.py, tests/platforms/test_ncm_radio.py, tests/platforms/test_platform.py, tests/platforms/test_rss.py, tests/platforms/test_weibo.py, tests/post/test_generate.py, tests/subs_io/test_cli.py, tests/test_merge_pic.py, tests/theme/test_themes.py
还有新问题，api报错是什么原因呀，nonebot2，llob
_Originally posted by @LeoWrDeom in https://github.com/MountainDash/nonebot-bison/issues/605#issuecomment-2272732766_
fix this
=> B站请求策略阶段行为优化

.devcontainer/devcontainer.json, .github/actions/build-docs/action.yml, .github/actions/build-frontend/action.yml, .github/actions/setup-node/action.yml, docker/Dockerfile
rt，我把项目中出现过 yarn 的地方都检查过了，但是我似乎也不方便验证有没有其他问题 （
=> :construction_worker: 将自动化工具中的 yarn 替换为 pnpm

nonebot_bison/platform/bilibili/platforms.py, tests/platforms/test_bilibili_live.py
将下播时的图片修改为封面
https://github.com/MountainDash/nonebot-bison/issues/626
=> B站直播无法获取关键帧时使用封面

nonebot_bison/platform/bilibili/models.py
=> 修正 opus 解析类型

docker/Dockerfile, docker/Dockerfile_without_browser
origin: https://github.com/MountainDash/nonebot-bison/pull/691
=> :bug: 尝试更新corepack

docker/grafana-dashboard-bison.json, docker/grafana-dashboard-nonebot.json, pyproject.toml, uv.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MountainDash/nonebot-bison/707)
=> :arrow_up: Update prometheus plugin to 0.3.16

docker/Dockerfile_without_browser, docs/usage/README.md, docs/usage/easy-use.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MountainDash/nonebot-bison/712)
=> :memo: 修复文档中 dotenv 格式的布尔值大小写问题

docker/Dockerfile, docker/Dockerfile_without_browser
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MountainDash/nonebot-bison/720)
=> 将 dockerfile 默认的 host 设为 0.0.0.0

nonebot_bison/theme/render_helper.py, nonebot_bison/theme/themes/arknights/build.py, nonebot_bison/theme/themes/arknights/templates/announce.html.jinja
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MountainDash/nonebot-bison/723)
=> 使 arknights theme 支持分离式渲染

nonebot_bison/platform/weibo.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MountainDash/nonebot-bison/725)
=> 将 weibo 的调度间隔减慢为 10s 一次

nonebot_bison/platform/ceobecanteen/platform.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/MountainDash/nonebot-bison/733)
=> :bug: fix full test
